menu:
    Blog: /
    Archive: /archives/
    WHOAMI: https://gisonrg.me/
    Rss: /atom.xml

favicon: /favicon.png
logo: /logo.png

# Comment
# e.g disqus: seansun
disqus: gisonrg
duoshuo:

# Analytics
# google-analytics:
ga: UA-65415714-2

# Copyright Infomation
startyear: 2015
